#!/usr/bin/env python3
"""Exact Weyl-orbit classification of maximum nonpositive E7 root subsets.

The 126 roots use integer coordinates of squared norm 8.  A maximum
pairwise-nonpositive subset is seven antipodal pairs on seven orthogonal
root lines (an X7).  This program enumerates all such line sets and proves
that the E7 Weyl group, generated by exact root reflections, acts
transitively on them.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
from collections import deque
from datetime import datetime, timezone
from pathlib import Path

import numpy as np


def e7_roots_scaled() -> np.ndarray:
    roots: list[np.ndarray] = []
    for i in range(8):
        for j in range(i + 1, 8):
            root = np.zeros(8, dtype=np.int64)
            root[i] = 2
            root[j] = -2
            roots.extend((root, -root))
    for plus in itertools.combinations(range(8), 4):
        root = -np.ones(8, dtype=np.int64)
        root[list(plus)] = 1
        roots.append(root)
    result = np.unique(np.asarray(roots, dtype=np.int64), axis=0)
    assert result.shape == (126, 8)
    assert np.all(np.sum(result * result, axis=1) == 8)
    assert np.all(np.sum(result, axis=1) == 0)
    return result


def enumerate_orthogonal_seven_sets(
    roots: np.ndarray,
) -> tuple[list[tuple[int, int]], list[tuple[int, ...]]]:
    root_index = {tuple(row.tolist()): i for i, row in enumerate(roots)}
    lines: list[tuple[int, int]] = []
    used: set[int] = set()
    for i, root in enumerate(roots):
        anti = root_index[tuple((-root).tolist())]
        representative = min(i, anti)
        if representative in used:
            continue
        used.add(representative)
        lines.append((min(i, anti), max(i, anti)))
    assert len(lines) == 63

    reps = roots[[line[0] for line in lines]]
    gram = reps @ reps.T
    adjacency: list[int] = []
    for i in range(len(lines)):
        bits = 0
        for j in range(len(lines)):
            if i != j and int(gram[i, j]) == 0:
                bits |= 1 << j
        adjacency.append(bits)

    forward = [bits & ~((1 << (i + 1)) - 1) for i, bits in enumerate(adjacency)]
    found: list[tuple[int, ...]] = []

    def recurse(clique: list[int], candidates: int) -> None:
        need = 7 - len(clique)
        if need == 0:
            found.append(tuple(clique))
            return
        if candidates.bit_count() < need:
            return
        while candidates:
            bit = candidates & -candidates
            vertex = bit.bit_length() - 1
            candidates ^= bit
            recurse(clique + [vertex], candidates & forward[vertex])

    recurse([], (1 << len(lines)) - 1)
    assert len(found) == 135
    return lines, found


def reflection_permutations(
    roots: np.ndarray,
    lines: list[tuple[int, int]],
) -> list[tuple[int, ...]]:
    root_index = {tuple(row.tolist()): i for i, row in enumerate(roots)}
    line_index: dict[int, int] = {}
    for index, (first, second) in enumerate(lines):
        line_index[first] = index
        line_index[second] = index
    reps = roots[[line[0] for line in lines]]

    permutations: set[tuple[int, ...]] = set()
    for alpha in roots:
        permutation: list[int] = []
        for root in reps:
            dot = int(root @ alpha)
            assert dot % 4 == 0
            reflected = root - (dot // 4) * alpha
            target = root_index[tuple(reflected.tolist())]
            permutation.append(line_index[target])
        assert sorted(permutation) == list(range(63))
        permutations.add(tuple(permutation))
    assert len(permutations) == 63  # alpha and -alpha induce the same reflection
    return sorted(permutations)


def orbit(
    seed: tuple[int, ...],
    generators: list[tuple[int, ...]],
) -> set[tuple[int, ...]]:
    seen = {tuple(sorted(seed))}
    queue: deque[tuple[int, ...]] = deque(seen)
    while queue:
        current = queue.popleft()
        for permutation in generators:
            image = tuple(sorted(permutation[index] for index in current))
            if image not in seen:
                seen.add(image)
                queue.append(image)
    return seen


def digest(items: list[tuple[int, ...]]) -> str:
    text = "\n".join(",".join(map(str, item)) for item in sorted(items)) + "\n"
    return hashlib.sha256(text.encode("ascii")).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    roots = e7_roots_scaled()
    lines, maxima = enumerate_orthogonal_seven_sets(roots)
    generators = reflection_permutations(roots, lines)
    reached = orbit(maxima[0], generators)
    maximum_set = set(maxima)
    assert reached == maximum_set

    witness_lines = maxima[0]
    witness_root_indices = [index for line in witness_lines for index in lines[line]]
    result = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "arithmetic": "integer only; reflection x -> x - (x.alpha/4) alpha",
        "e7_root_count": 126,
        "e7_root_line_count": 63,
        "maximum_nonpositive_subset_size": 14,
        "maximum_line_set_size": 7,
        "maximum_x7_count": len(maxima),
        "distinct_root_reflections": len(generators),
        "orbit_size_from_one_x7": len(reached),
        "weyl_transitive_on_x7": reached == maximum_set,
        "maximum_sets_sha256": digest(maxima),
        "witness_line_indices": list(witness_lines),
        "witness_root_indices": witness_root_indices,
        "witness_vectors_scaled": roots[witness_root_indices].tolist(),
        "consequence": (
            "All 135 complements of an X7 in the E7 root system are isometric "
            "under exact root reflections. Changing only which 14 E7 roots are "
            "omitted cannot change the standalone rank-7 cap problem."
        ),
        "exact": True,
    }
    text = json.dumps(result, indent=2, sort_keys=True)
    print(text)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
