#!/usr/bin/env python3
"""Exact partition-orbit classification for saturated E6/E7 product fibers.

PackingStar's 1,008-point dimension-13 product core decomposes into eight
K_{9,14} components.  On the E6 side this partitions all 72 roots into eight
maximum nine-root Y3 subsets.  On the E7 side, after restoring the omitted
14-root X7, it partitions the 63 antipodal root lines into nine orthogonal
seven-line X7 subsets.

This program enumerates every such exact cover and classifies it under the
Weyl group generated by exact root reflections.  All computations are over
integers; no floating point is used.
"""
from __future__ import annotations

import argparse
import hashlib
import itertools
import json
from collections import Counter, deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import numpy as np


def e7_roots_scaled() -> np.ndarray:
    roots: list[np.ndarray] = []
    for i in range(8):
        for j in range(i + 1, 8):
            root = np.zeros(8, dtype=np.int64)
            root[i] = 2
            root[j] = -2
            roots.extend((root, -root))
    for plus in itertools.combinations(range(8), 4):
        root = -np.ones(8, dtype=np.int64)
        root[list(plus)] = 1
        roots.append(root)
    result = np.unique(np.asarray(roots, dtype=np.int64), axis=0)
    assert result.shape == (126, 8)
    assert np.all(np.sum(result * result, axis=1) == 8)
    assert np.all(np.sum(result, axis=1) == 0)
    return result


def e6_roots_scaled() -> np.ndarray:
    roots = e7_roots_scaled()
    result = roots[roots[:, 6] + roots[:, 7] == 0]
    assert result.shape == (72, 8)
    return result


def enumerate_cliques(
    adjacency: list[int], size: int
) -> list[tuple[int, ...]]:
    forward = [bits & ~((1 << (i + 1)) - 1) for i, bits in enumerate(adjacency)]
    found: list[tuple[int, ...]] = []

    def recurse(clique: list[int], candidates: int) -> None:
        need = size - len(clique)
        if need == 0:
            found.append(tuple(clique))
            return
        if candidates.bit_count() < need:
            return
        while candidates:
            bit = candidates & -candidates
            vertex = bit.bit_length() - 1
            candidates ^= bit
            recurse(clique + [vertex], candidates & forward[vertex])

    recurse([], (1 << len(adjacency)) - 1)
    return found


def exact_covers(
    universe_size: int, blocks: list[tuple[int, ...]]
) -> tuple[list[tuple[int, ...]], int]:
    masks = [sum(1 << vertex for vertex in block) for block in blocks]
    containing: list[list[int]] = [[] for _ in range(universe_size)]
    for index, block in enumerate(blocks):
        for vertex in block:
            containing[vertex].append(index)
    full = (1 << universe_size) - 1
    covers: list[tuple[int, ...]] = []
    nodes = 0

    def recurse(used: int, chosen: list[int]) -> None:
        nonlocal nodes
        nodes += 1
        if used == full:
            covers.append(tuple(sorted(chosen)))
            return
        remaining = full ^ used
        options: list[int] | None = None
        while remaining:
            bit = remaining & -remaining
            vertex = bit.bit_length() - 1
            remaining ^= bit
            compatible = [i for i in containing[vertex] if not (masks[i] & used)]
            if not compatible:
                return
            if options is None or len(compatible) < len(options):
                options = compatible
            if len(options) == 1:
                break
        assert options is not None
        for index in options:
            recurse(used | masks[index], chosen + [index])

    recurse(0, [])
    return sorted(covers), nodes


def root_reflection_permutations(roots: np.ndarray) -> list[tuple[int, ...]]:
    index = {tuple(root.tolist()): i for i, root in enumerate(roots)}
    permutations: set[tuple[int, ...]] = set()
    for alpha in roots:
        permutation: list[int] = []
        for root in roots:
            dot = int(root @ alpha)
            assert dot % 4 == 0
            reflected = root - (dot // 4) * alpha
            permutation.append(index[tuple(reflected.tolist())])
        assert sorted(permutation) == list(range(len(roots)))
        permutations.add(tuple(permutation))
    return sorted(permutations)


def line_reflection_permutations(
    roots: np.ndarray, lines: list[tuple[int, int]]
) -> list[tuple[int, ...]]:
    root_index = {tuple(root.tolist()): i for i, root in enumerate(roots)}
    line_index = {root: i for i, line in enumerate(lines) for root in line}
    representatives = roots[[line[0] for line in lines]]
    permutations: set[tuple[int, ...]] = set()
    for alpha in roots:
        permutation: list[int] = []
        for root in representatives:
            dot = int(root @ alpha)
            assert dot % 4 == 0
            reflected = root - (dot // 4) * alpha
            permutation.append(line_index[root_index[tuple(reflected.tolist())]])
        assert sorted(permutation) == list(range(len(lines)))
        permutations.add(tuple(permutation))
    return sorted(permutations)


def induced_block_permutations(
    blocks: list[tuple[int, ...]], generators: list[tuple[int, ...]]
) -> list[tuple[int, ...]]:
    block_index = {tuple(sorted(block)): i for i, block in enumerate(blocks)}
    result: list[tuple[int, ...]] = []
    for permutation in generators:
        image = tuple(
            block_index[tuple(sorted(permutation[vertex] for vertex in block))]
            for block in blocks
        )
        assert sorted(image) == list(range(len(blocks)))
        result.append(image)
    return result


def classify_cover_orbits(
    covers: list[tuple[int, ...]], block_generators: list[tuple[int, ...]]
) -> list[list[tuple[int, ...]]]:
    cover_set = set(covers)
    unseen = set(covers)
    orbits: list[list[tuple[int, ...]]] = []
    while unseen:
        seed = min(unseen)
        seen = {seed}
        queue: deque[tuple[int, ...]] = deque([seed])
        while queue:
            current = queue.popleft()
            for permutation in block_generators:
                image = tuple(sorted(permutation[index] for index in current))
                assert image in cover_set
                if image not in seen:
                    seen.add(image)
                    queue.append(image)
        unseen -= seen
        orbits.append(sorted(seen))
    return sorted(orbits, key=lambda orbit: (len(orbit), orbit[0]))


def classify_flag_orbits(
    covers: list[tuple[int, ...]], block_generators: list[tuple[int, ...]]
) -> list[list[tuple[tuple[int, ...], int]]]:
    flags = sorted((cover, block) for cover in covers for block in cover)
    flag_set = set(flags)
    unseen = set(flags)
    orbits: list[list[tuple[tuple[int, ...], int]]] = []
    while unseen:
        seed = min(unseen)
        seen = {seed}
        queue: deque[tuple[tuple[int, ...], int]] = deque([seed])
        while queue:
            cover, distinguished = queue.popleft()
            for permutation in block_generators:
                image = (
                    tuple(sorted(permutation[index] for index in cover)),
                    permutation[distinguished],
                )
                assert image in flag_set
                if image not in seen:
                    seen.add(image)
                    queue.append(image)
        unseen -= seen
        orbits.append(sorted(seen))
    return sorted(orbits, key=lambda orbit: (len(orbit), orbit[0]))


def pair_profile_signature(
    gram: np.ndarray,
    blocks: list[tuple[int, ...]],
    cover: tuple[int, ...],
) -> dict[str, int]:
    profiles: Counter[str] = Counter()
    selected = [blocks[index] for index in cover]
    for first, second in itertools.combinations(selected, 2):
        values, counts = np.unique(gram[np.ix_(first, second)], return_counts=True)
        profile = ",".join(f"{int(v)}:{int(c)}" for v, c in zip(values, counts))
        profiles[profile] += 1
    return dict(sorted(profiles.items()))


def digest(items: Iterable[tuple[int, ...]]) -> str:
    text = "\n".join(",".join(map(str, item)) for item in sorted(items)) + "\n"
    return hashlib.sha256(text.encode("ascii")).hexdigest()


def e7_partition_result() -> dict:
    roots = e7_roots_scaled()
    root_index = {tuple(root.tolist()): i for i, root in enumerate(roots)}
    lines: list[tuple[int, int]] = []
    seen: set[int] = set()
    for i, root in enumerate(roots):
        antipode = root_index[tuple((-root).tolist())]
        representative = min(i, antipode)
        if representative in seen:
            continue
        seen.add(representative)
        lines.append((min(i, antipode), max(i, antipode)))
    assert len(lines) == 63
    reps = roots[[line[0] for line in lines]]
    gram = reps @ reps.T
    adjacency = [
        sum(1 << j for j in range(63) if i != j and int(gram[i, j]) == 0)
        for i in range(63)
    ]
    blocks = enumerate_cliques(adjacency, 7)
    assert len(blocks) == 135
    covers, nodes = exact_covers(63, blocks)
    assert len(covers) == 960
    generators = line_reflection_permutations(roots, lines)
    assert len(generators) == 63
    block_generators = induced_block_permutations(blocks, generators)
    orbits = classify_cover_orbits(covers, block_generators)
    assert [len(orbit) for orbit in orbits] == [960]
    flag_orbits = classify_flag_orbits(covers, block_generators)
    assert [len(orbit) for orbit in flag_orbits] == [8640]
    return {
        "root_count": 126,
        "root_line_count": 63,
        "maximum_x7_blocks": len(blocks),
        "x7_partitions": len(covers),
        "exact_cover_search_nodes": nodes,
        "root_reflection_generators": len(generators),
        "weyl_orbit_count": len(orbits),
        "weyl_orbit_sizes": [len(orbit) for orbit in orbits],
        "all_partitions_isometric": True,
        "flagged_partition_count": 8640,
        "flagged_partition_orbit_count": len(flag_orbits),
        "flagged_partition_orbit_sizes": [len(orbit) for orbit in flag_orbits],
        "omitted_x7_choice_is_transitive": True,
        "blocks_sha256": digest(blocks),
        "partitions_sha256": digest(covers),
        "witness_partition_block_indices": list(orbits[0][0]),
    }


def e6_partition_result() -> dict:
    roots = e6_roots_scaled()
    gram = roots @ roots.T
    adjacency = [
        sum(1 << j for j in range(72) if i != j and int(gram[i, j]) <= 0)
        for i in range(72)
    ]
    blocks = enumerate_cliques(adjacency, 9)
    assert len(blocks) == 320
    covers, nodes = exact_covers(72, blocks)
    assert len(covers) == 17920
    generators = root_reflection_permutations(roots)
    assert len(generators) == 36
    block_generators = induced_block_permutations(blocks, generators)
    orbits = classify_cover_orbits(covers, block_generators)
    expected_sizes = [40, 360, 480, 480, 480, 960, 1440, 1440, 1440, 2160, 2880, 2880, 2880]
    assert [len(orbit) for orbit in orbits] == expected_sizes
    orbit_rows = []
    for index, orbit in enumerate(orbits):
        witness = orbit[0]
        signature = pair_profile_signature(gram, blocks, witness)
        orbit_rows.append(
            {
                "orbit_index": index,
                "orbit_size": len(orbit),
                "witness_partition_block_indices": list(witness),
                "pair_profile_signature": signature,
                "pair_profile_sha256": hashlib.sha256(
                    json.dumps(signature, sort_keys=True).encode("utf-8")
                ).hexdigest(),
            }
        )
    return {
        "root_count": 72,
        "maximum_y3_blocks": len(blocks),
        "y3_partitions": len(covers),
        "exact_cover_search_nodes": nodes,
        "root_reflection_generators": len(generators),
        "weyl_orbit_count": len(orbits),
        "weyl_orbit_sizes": expected_sizes,
        "all_partitions_isometric": False,
        "blocks_sha256": digest(blocks),
        "partitions_sha256": digest(covers),
        "orbits": orbit_rows,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    result = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "arithmetic": "integer only",
        "exact": True,
        "E7_X7_partitions": e7_partition_result(),
        "E6_Y3_partitions": e6_partition_result(),
        "consequence": (
            "The E7 side of every saturated product core has one partition geometry, "
            "even after distinguishing the omitted X7, while the E6 side has exactly "
            "13 Weyl-inequivalent partition geometries. Local X7/Y3 choices alone are "
            "therefore insufficient; only the E6 global partition orbit and cap "
            "coupling remain as discrete product-core freedom."
        ),
    }
    text = json.dumps(result, indent=2, sort_keys=True)
    print(text)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
